spring:
  application:
    name: poc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enable: false
  datasource:
    url: jdbc:mysql://localhost:3306/poc?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: admin